enable_selector = false
selector = "fuzzel -dmenu -i -p 'Open With: '"
term_exec_args = '-e'
expand_wildcards = false

[[handlers]]
exec = "mpv %u"
terminal = false
regexes = ['(https://)?(www\.)?youtu(be\.com|\.be)/*.']

[[handlers]]
exec = "tor-browser %u"
terminal = false
regexes = ['https://.*\.onion']

[[handlers]]
exec = "librewolf %u"
terminal = false
regexes = [
  'http://.*',
  '(https://)?(www\.)?bsky.app/.*',
  '(https://)?(www\.)?github.com/.*',
  '(https://)?(.*\.)?reddit.com/.*',
  '(https://)?(.*\.)?spotify.com/.*',
]
