theme = "monokai"

[editor]
line-number = "relative"
mouse = false
true-color = true
bufferline = "multiple"
color-modes = true

[editor.cursor-shape]
insert = "bar"

[keys.normal]
";" = "command_mode"
"esc" = ["collapse_selection", "keep_primary_selection"]
"H" = ["extend_to_first_nonwhitespace"]
"L" = ["extend_to_line_end"]
"D" = ["extend_to_line_end", "delete_selection"]
"C" = ["extend_to_line_end", "delete_selection", "insert_mode"]
"N" = ["search_prev", "align_view_center"]
"n" = ["search_next", "align_view_center"]
