theme = "monokai"

[editor]
line-number = "relative"
mouse = false
true-color = true
bufferline = "multiple"
color-modes = true

[editor.cursor-shape]
insert = "bar"

[keys.normal]
";" = "command_mode"
"esc" = ["collapse_selection", "keep_primary_selection"]
